updated bitbucket pipeline to detect code changes

diff --git a/bitbucket-pipelines.yml b/bitbucket-pipelines.yml
--- a/bitbucket-pipelines.yml
+++ b/bitbucket-pipelines.yml
@@ -125,13 +125,13 @@ pipelines:
             - terraform init -backend-config="bucket=$TF_BACKEND_BUCKET" -backend-config="region=$AWS_DEFAULT_REGION"
             - terraform plan -var-file="dev.tfvars" -out=tfplan
             - |
-              if [ $? -eq 0 ]; then
-                echo "No changes detected, skipping apply."
-              elif [ $? -eq 2 ]; then
-                echo "Changes detected, applying..."
-                terraform apply -var-file="dev.tfvars" -auto-approve
+              if [ $? -eq 2 ]; then
+                echo "Changes detected in the plan. Applying changes..."
+                terraform apply -auto-approve tfplan
+              elif [ $? -eq 0 ]; then
+                echo "No changes detected. Skipping apply."
               else
-                echo "Error during plan. Exiting."
+                echo "An error occurred during the plan step. Exiting."
                 exit 1
               fi
 
